### ISSUE TITLE
[BUG]: Code quality

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise-usb#107]
### Describe the bug.

Replacing black with `ruff` not viable yet  - also `mypy` and `coverage` (as there is lack of testing for prolonged time now) #106 prepared this but ruff is effectively disabled in `.github/workflows/verify` now.

Disabled in pre-commit and GH action verify

### Expected behavior

Ensure proper code along HA standards

### Todo

- [] Make code `ruff` compatible
- [] Make code `mypy` compatible
- [] Finally make some tests so we have coverage to test for
