### ISSUE TITLE
[TODO]: Improve time handling

### ISSUE THREAD

**Issue by CoMPaTech** [plugwise/python-plugwise-usb#173]
### Todo

As signalled by CodeRabbitAI:
- [x] https://github.com/plugwise/python-plugwise-usb/pull/170#discussion_r1703317809
- [x] https://github.com/plugwise/python-plugwise-usb/pull/170#discussion_r1703317810
- [x] https://github.com/plugwise/python-plugwise-usb/pull/170#discussion_r1703317811
